Task 2.5 product list page
dramantsevich/phoneshop pull request #2
Opened 2022-06-07 10:17 UTC by dramantsevich

2022-06-08 13:41 UTC, katcinskiy commented on core/src/main/java/com/es/core/model/phone/PhoneDao.java
> +    Stock getPhoneById(Long key);
для работы со стоками лучше сделать отдельный StockDao

2022-06-08 13:44 UTC, katcinskiy commented on core/src/main/java/com/es/core/cart/CartItem.java
> +    private Stock stock;
если будешь хранить сток тут, то не будет синхронизации между пользователями, если они будут добавлять один и тот же товар

2022-06-08 13:56 UTC, katcinskiy commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        if (cart == null) {
используй optional тут

2022-06-21 09:30 UTC, katcinskiy requested changes

2022-06-21 09:30 UTC, katcinskiy commented on core/src/test/java/com/es/phoneshop/ProductDaoTest.java
> +        Page<Stock> stockPage = createPageWithStockPhones();
display phones with stock > 0 only, сделай тест для проверки этого

2022-06-21 09:30 UTC, katcinskiy commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +        if ((sort != null && !sort.equals("")) && (order != null && !order.equals(""))) {
используй SpringUtils чтобы проверить сразу на нул и на пустую строку

2022-06-21 09:30 UTC, katcinskiy commented on web/src/main/webapp/WEB-INF/pages/productList.jsp
> +                        <input id="${ph.phone.id}" type="number" class="quantity" name="quantity"/>
requirenment: No html5 inputs please...

2022-06-21 09:30 UTC, katcinskiy commented on web/src/main/webapp/WEB-INF/pages/search.jsp
> +<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
мне кажется тут много дурликатов с productList.jsp, было бы хорошо избегать дублирования, в jsp кажется можно вынести фрагмент кода в другой jsp

2022-06-21 09:30 UTC, katcinskiy commented on core/src/main/java/com/es/core/dao/cart/CartService.java
> +public interface CartService {
в package dao не нужно класть сервисы, вынеси их в отдельный пекедж service

2022-06-21 09:30 UTC, katcinskiy commented on core/src/main/java/com/es/core/dao/cart/DefaultCartService.java
> +        Stock phone = stockDao.getPhoneById(phoneId).orElseThrow(NullPointerException::new);
NullPointer выбрасывать не надо, без тебя он сам может выпасть, лучше сделать специальное исключение

2022-06-21 09:30 UTC, katcinskiy commented on core/src/main/java/com/es/core/dao/stock/JdbcStockDao.java
> +                "where s.stock > 0\n" + withPrice +
в запросах скл лучше использовать named parametres(MapSqlParameterSource) чтобы избежать sql injection и также кажется у тебя много дупликатов в скл, в таком случае лучше вынести дублирующий код в отдельный метод или константу

2022-06-21 09:30 UTC, katcinskiy commented on web/src/main/java/com/es/phoneshop/web/controller/pages/SearchController.java
> +        if ((sort != null && !sort.equals("")) && (order != null && !order.equals(""))) {
если хочешь стрингу проверить на нул и на пустоту то можешь использовать Objects.isEmpty() из спринга

2022-06-21 09:30 UTC, katcinskiy commented on web/src/main/java/com/es/phoneshop/web/controller/pages/admin/LoginPageController.java
> +        String userName = request.getParameter("userName");
используй @RequestParam лучше

2022-06-21 09:30 UTC, katcinskiy commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +    @Transactional
в этом Transactional нету смысла

2022-06-21 09:30 UTC, katcinskiy commented on core/src/main/java/com/es/core/dao/order/OrderServiceImpl.java
> +                    jdbcTemplate.update("update stocks \n" +
не нужно выполнять запросы к базе в сервисе, это должен делать дао. Так как, например, если ты изменишь базу данных, то тебе придется заменить не только ДАО классы, но теперь уже и сервисы

2022-06-21 11:32 UTC, dramantsevich commented on web/src/main/webapp/WEB-INF/pages/search.jsp
> +<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
код похож, но не идентичен
1) в шапке таблицы используются разные тэги для соритровки
2) контент таблицы реализован через foreach и выборке различных полей объекта + кнопка добавления принимает разные поля, при выделении этой части кода в отдельную jsp контент не подгружается(если через tag, то эксепшн выкидывается)
3) пагинация, используется разная пагинация, т.к. для страницы search необходимо каждый раз использовать слово по которому ищем продукты
поэтому, на мой взгляд, вынесение кода не подойдет

2022-06-21 15:38 UTC, katcinskiy commented on core/src/main/java/com/es/core/service/impl/cart/HttpSessionCartServiceImpl.java
> +        if (quantity == null) {
такие легкие проверки лучше выносить на уровень валидатора spring mvc

2022-06-21 15:43 UTC, katcinskiy commented on core/src/main/java/com/es/core/service/impl/cart/DefaultCartService.java
> +        CartItem cartItem = new CartItem(phone, quantity);
есть ли смысл создавать эту переменную? cartItem

2022-06-21 15:46 UTC, katcinskiy commented on core/src/main/java/com/es/core/service/impl/cart/HttpSessionCartServiceImpl.java
> +        CartItem cartItem = new CartItem(phone, quantity.intValue());
а в чем смысл принимать Long и потом переводить его в int? тогда уже лучше принимать int или хранить quantity as long

2022-06-21 15:51 UTC, katcinskiy commented on core/src/main/java/com/es/core/service/impl/cart/HttpSessionCartServiceImpl.java
> +        if ((phone.getStock() - phone.getReserved()) < quantityLong) {
предлагаю вынести часть дублирующего кода из update и addPhone в отдельный приватный метод в этом же классе, потому что его тут довольно много(дупликата)

2022-06-21 15:56 UTC, katcinskiy commented on core/src/main/java/com/es/core/service/impl/order/DefaultOrderService.java
> +            item.setId(++orderId);
а что если это вызовется синхронно в нескольких потоках?(для каждого юзера создается отдельный поток). твоя переменная

2022-06-21 16:09 UTC, katcinskiy commented on core/src/main/java/com/es/core/service/impl/order/OrderServiceImpl.java
> +            order.setItems(cartItemList);
эту популяцию order разве нужно делать в цикле?

2022-06-21 16:18 UTC, katcinskiy commented on core/src/main/java/com/es/core/service/impl/order/OrderServiceImpl.java
> +                int updateReserved = reserved - quantity;
1. разве может быть reserved у ордера? товары ведь по сути уже заказаны
2. разве не нужно при reject выкладывать ВСЕ товары обратно в сток?

2022-06-21 16:19 UTC, katcinskiy commented on core/src/main/java/com/es/core/service/impl/order/OrderServiceImpl.java
> +                if ((stock - reserved) < quantity) {
тогда такой ситуации не должно случится вовсе

2022-06-21 16:20 UTC, katcinskiy commented on core/src/main/java/com/es/core/validation/cartitem/QuantityValidation.java
> +public @interface QuantityValidation {
это используется разве где-нибудь?

2022-06-21 16:20 UTC, katcinskiy commented on core/src/main/java/com/es/core/validation/cartitem/CartItemValidator.java
> +public class CartItemValidator implements Validator {
это используется разве где-нибудь?

2022-06-21 16:26 UTC, katcinskiy commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +        model.addAttribute("cart", cart);
зачем тут сетать карту в модель?

2022-06-21 16:27 UTC, katcinskiy commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +    @RequestMapping(method = RequestMethod.POST, produces = "application/json", consumes = "application/json")
вместо "application/json" лучше использовать константы в спринге. а вообще, если у тебя RestController, то эти значения будут по дефолту

2022-06-21 16:51 UTC, katcinskiy commented on core/src/test/java/com/es/phoneshop/CartTest.java
> +        doNothing()
не совсем понимаю, этот тест ведь ничего не проверяет, мокаешь метод и потом проверяешь что мок работает

2022-06-21 16:51 UTC, katcinskiy commented on core/src/test/java/com/es/phoneshop/CartTest.java
> +        doNothing()
не совсем понимаю, этот тест ведь ничего не проверяет, мокаешь метод и потом проверяешь что мок работает

2022-06-21 16:52 UTC, katcinskiy commented on core/src/test/java/com/es/phoneshop/CartTest.java
> +        doNothing().when(mockCartService).addPhone(cart, id, quantity);
не совсем понимаю, этот тест ведь ничего не проверяет, мокаешь метод и потом проверяешь что мок работает

2022-06-21 16:54 UTC, katcinskiy commented on core/src/main/java/com/es/core/service/impl/cart/DefaultCartService.java
> +        if (quantity <= 0) {
в документе:

Use annotations to do basic validation (e.g. @MinValue(1))

2022-06-27 09:39 UTC, katcinskiy commented on core/src/main/java/com/es/core/service/impl/order/DefaultOrderService.java
> +    public Order getItem(Long id) {
это будет работать настолько же медленно как и версия с массивом, необходимо сделать поиск быстрее, используя преимущества Map

2022-06-27 09:51 UTC, katcinskiy commented on core/src/test/java/com/es/phoneshop/integration/CartServiceTest.java
> +@ContextConfiguration(locations = "classpath:/testContext.xml")
исправлять уже не надо, но знай, что необходимо переносить структуру приложения на структуру тестов, например если у тебя сервис лежит по my/package/service/cart/Service.java, то тесты должны лежать так:

my/package/service/cart/ServiceUnitTest.java
my/package/service/cart/ServiceIntegrationTest.java

2022-06-27 10:00 UTC, katcinskiy commented on core/src/test/java/com/es/phoneshop/unit/CartTest.java
> +public class CartTest {
все 3 теста не имеют смысла, тестируются по сути моки, необходимо тестировать сервис

2022-06-28 13:30 UTC, merged